version: "3.9"
name: tech-chalenge4
services:
  cliente-app:
    image: clienteapi/latest
    depends_on:
      - mongodb
    build:
      context: ./gerenciamentopedidos.cliente
      dockerfile: Dockerfile
    command: --spring.profiles.active=prod
    ports:
      - "8084:8084"
    networks:
      - prod

  produto-app:
    image: produto/latest
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./gerenciamentopedidos.produto
      dockerfile: Dockerfile
    command: --spring.profiles.active=prod
    ports:
      - "8083:8083"
    networks:
      - prod

  trajeto-app:
    image: trajeto/latest
    depends_on:
      - mongodb
    build:
      context: ./gerenciamentopedidos.trajeto
      dockerfile: Dockerfile
    command: --spring.profiles.active=prod
    ports:
      - "8082:8082"
    networks:
      - prod

  pedidos-app:
    image: pedidos/latest
    depends_on:
      mysqldb:
        condition: service_healthy
      produto-app:
        condition: service_started
      cliente-app:
        condition: service_started
      trajeto-app:
        condition: service_started
    build:
      context: ./gerenciamentopedidos
      dockerfile: Dockerfile
    command: --spring.profiles.active=prod
    ports:
      - "8081:8081"
    networks:
      - prod

  gateway-app:
    image: gateway/latest
    depends_on:
      - pedidos-app
      - cliente-app
      - produto-app
      - trajeto-app
    build:
      context: ./gerenciamentopedidos.gateway
      dockerfile: Dockerfile
    command: --spring.profiles.active=prod
    ports:
      - "8080:8080"
    networks:
      - prod

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - prod

  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /data/application/init.sql
    volumes:
      - ./sql/prod.sql:/data/application/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - prod

networks:
  prod:
    driver: bridge