FROM openjdk:17-jdk-slim as setup

RUN apt-get update -y --fix-missing && apt-install wget
RUN wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
RUN tar -xvf apache-maven-3.6.3-bin.tar.gz
RUN mv apache-maven-3.6.3 /opt/

RUN M2_HOME='/opt/apache-maven-3.6.3'
RUN PATH="$M2_HOME/bin:$PATH"
RUN export PATH

FROM setup as build

COPY . /opt/project

WORKDIR /opt/project

RUN mvn package -B

ENTRYPOINT ["mvn", "spring-boot:run", "test"]